"""create tables

Revision ID: 13f388a64569
Revises: 
Create Date: 2026-04-25 18:18:46.843898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f388a64569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('mcc_code', sa.String(length=4), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('registered_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('employee_count_est', sa.Integer(), nullable=True),
    sa.Column('monthly_revenue_est_uzs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_businesses_mcc_city_active', 'businesses', ['mcc_code', 'city', 'is_active'], unique=False)
    op.create_index('ix_businesses_mcc_closed', 'businesses', ['mcc_code', 'closed_date'], unique=False)
    op.create_index('ix_businesses_niche_lat_lon', 'businesses', ['niche', 'lat', 'lon'], unique=False)
    op.create_table('customer_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_name', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('avg_monthly_spending_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('purchase_frequency_monthly', sa.Float(), nullable=False),
    sa.Column('avg_check_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('top_mcc_categories', sa.JSON(), nullable=False),
    sa.Column('spending_distribution', sa.JSON(), nullable=False),
    sa.Column('estimated_count', sa.Integer(), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_segments_city_district', 'customer_segments', ['city', 'district'], unique=False)
    op.create_index('ix_customer_segments_lat_lon', 'customer_segments', ['lat', 'lon'], unique=False)
    op.create_index('ix_customer_segments_name_city', 'customer_segments', ['segment_name', 'city'], unique=False)
    op.create_table('market_benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mcc_code', sa.String(length=4), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('avg_monthly_revenue_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('median_monthly_revenue_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('p25_monthly_revenue_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('p75_monthly_revenue_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('avg_monthly_transactions', sa.Integer(), nullable=False),
    sa.Column('avg_check_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_margin_pct', sa.Float(), nullable=False),
    sa.Column('avg_employee_count', sa.Float(), nullable=False),
    sa.Column('revenue_per_sqm_monthly_uzs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_growth_rate_pct', sa.Float(), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcc_code', 'city', 'data_year', name='uq_benchmark_mcc_city_year')
    )
    op.create_index('ix_market_benchmarks_niche_city', 'market_benchmarks', ['niche', 'city'], unique=False)
    op.create_table('market_size_estimates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('mcc_code', sa.String(length=4), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('tam_uzs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('sam_uzs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('som_uzs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('competitor_count', sa.Integer(), nullable=False),
    sa.Column('market_growth_rate_pct', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('calc_metadata', sa.JSON(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_estimates_lat_lon', 'market_size_estimates', ['lat', 'lon'], unique=False)
    op.create_index('ix_market_estimates_niche_city_date', 'market_size_estimates', ['niche', 'city', 'calculation_date'], unique=False)
    op.create_table('mcc_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcc_code', sa.String(length=4), nullable=False),
    sa.Column('category_name_en', sa.String(length=100), nullable=False),
    sa.Column('niche_name_uz', sa.String(length=100), nullable=False),
    sa.Column('niche_name_ru', sa.String(length=100), nullable=False),
    sa.Column('parent_category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcc_code')
    )
    op.create_table('points_of_interest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('poi_type', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('capacity_est', sa.Integer(), nullable=True),
    sa.Column('daily_visitors_est', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_poi_lat_lon', 'points_of_interest', ['lat', 'lon'], unique=False)
    op.create_index('ix_poi_type_city', 'points_of_interest', ['poi_type', 'city'], unique=False)
    op.create_table('population_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('working_age_population', sa.Integer(), nullable=False),
    sa.Column('youth_population', sa.Integer(), nullable=False),
    sa.Column('avg_monthly_income_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('avg_monthly_spending_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_population_zones_city_district', 'population_zones', ['city', 'district'], unique=False)
    op.create_index('ix_population_zones_lat_lon', 'population_zones', ['lat', 'lon'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mcc_code', sa.String(length=4), nullable=False),
    sa.Column('merchant_lat', sa.Float(), nullable=True),
    sa.Column('merchant_lon', sa.Float(), nullable=True),
    sa.Column('merchant_district', sa.String(length=100), nullable=True),
    sa.Column('merchant_city', sa.String(length=100), nullable=False),
    sa.Column('customer_age_group', sa.String(length=10), nullable=True),
    sa.Column('customer_gender', sa.String(length=1), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcc_code'], ['mcc_categories.mcc_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_city_mcc_date', 'transactions', ['merchant_city', 'mcc_code', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_lat_lon', 'transactions', ['merchant_lat', 'merchant_lon'], unique=False)
    op.create_index('ix_transactions_mcc_date', 'transactions', ['mcc_code', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_mcc_date', table_name='transactions')
    op.drop_index('ix_transactions_lat_lon', table_name='transactions')
    op.drop_index('ix_transactions_city_mcc_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_population_zones_lat_lon', table_name='population_zones')
    op.drop_index('ix_population_zones_city_district', table_name='population_zones')
    op.drop_table('population_zones')
    op.drop_index('ix_poi_type_city', table_name='points_of_interest')
    op.drop_index('ix_poi_lat_lon', table_name='points_of_interest')
    op.drop_table('points_of_interest')
    op.drop_table('mcc_categories')
    op.drop_index('ix_market_estimates_niche_city_date', table_name='market_size_estimates')
    op.drop_index('ix_market_estimates_lat_lon', table_name='market_size_estimates')
    op.drop_table('market_size_estimates')
    op.drop_index('ix_market_benchmarks_niche_city', table_name='market_benchmarks')
    op.drop_table('market_benchmarks')
    op.drop_index('ix_customer_segments_name_city', table_name='customer_segments')
    op.drop_index('ix_customer_segments_lat_lon', table_name='customer_segments')
    op.drop_index('ix_customer_segments_city_district', table_name='customer_segments')
    op.drop_table('customer_segments')
    op.drop_index('ix_businesses_niche_lat_lon', table_name='businesses')
    op.drop_index('ix_businesses_mcc_closed', table_name='businesses')
    op.drop_index('ix_businesses_mcc_city_active', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
